os:
  - linux
  - osx
language: node_js
node_js:
  - lts/*
cache:
  npm: false
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:rwky/graphicsmagick -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install graphicsmagick -y; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install --build-from-source graphicsmagick; fi
install: npm ci