name: Memerizer Deployment

on:
  push:
    branches: [master, main]

  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
    - uses: actions/checkout@v3
    - name: Using Node.js (LTS) ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing required packages for node canvas
      run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev -y && npm install canvas --build-from-source
      shell: bash

    - name: Installing packages
      run: npm install
      shell: bash

    - name: Running tests
      run: npm test
      shell: bash
