name: Memerizer Deployment

on:
  push:
    branches: [master, main]

  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [lts/*]

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
    - uses: actions/checkout@v3
    - name: Using Node.js (LTS) ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing required packages, including GraphicsMagick and node Canvas
      run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install graphicsmagick -y
            && sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev -y
            && npm install --build-from-source
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install graphicsmagick
            && brew install pkg-config cairo pango libpng jpeg giflib librsvg
            && npm install --build-from-source
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
      shell: bash

    - name: Running tests
      run: npm test
      shell: bash
